export enum TokenType {
  DECLARATION = "DECLARATION",
  IDENTIFIER = "IDENTIFIER",
  COLON = "COLON",
  CONSTANT = "CONSTANT",
  STRING = "STRING",
  DOT = "DOT",
  BRACKET_ROUND_OPEN = "BRACKET_ROUND_OPEN",
  KEYWORD = "KEYWORD",
  BRACKET_ROUND_CLOSE = "BRACKET_ROUND_CLOSE",
  BRACKET_SQUARE_OPEN = "BRACKET_SQUARE_OPEN",
  BRACKET_SQUARE_CLOSE = "BRACKET_SQUARE_CLOSE",
  DECORATOR = "DECORATOR",
  COMMA = "COMMA",
  INTEGER = "INTEGER",
}

export type Token = {
  type: TokenType;
  value: string;
};
