export default {
  ERR0001: `Unable to find the raw code to be compiled`,
  ERR0002: `'rawCode' not provided`,
  ERR0003: `Make sure the code is wrapped in <script type="text/texscript">...</script>`,
  ERR0004: `'codeLOC' not provided`,
  ERR0005: `'rule' not provided`,
  ERR0006: `'matches' not provided`,
  ERR0007: `'tokens' not provided`,
  ERR0008: `token.type is null`,
  ERR0009: `'ast' is not provided`,
  ERR0010: `'node' is not provided`,
  ERR0011: `'lang' is not provided`,
  ERR0012: `Code generator for mentioned language is not provided`,
  ERR0013: `'metricsName' not provided`,
  ERR0014: `Unable to find any code written in Texscript`,
  ERR0015: `Not able to find anything inside <script> element`,
  ERR0016: `<script> element not found`,
};
